version: '3.3'

services:

  nginx:
    image: ${DOCKER_IMAGE_PREFIX}_nginx:${DOCKER_TAG}
    container_name: ${DOCKER_CONTAINER_PREFIX}_nginx
    restart: always
    build:
      context: ./../
      dockerfile: ./devops/nginx/Dockerfile
    volumes:
      - ./../dist:/var/www/html
    ports:
      - ${APP_REST_PORT}:80

  nodejs:
    image: ${DOCKER_IMAGE_PREFIX}_nodejs:${DOCKER_TAG}
    container_name: ${DOCKER_CONTAINER_PREFIX}_nodejs
    build:
      context: ./../
      dockerfile: ./devops/nodejs/Dockerfile
    volumes:
      - ./..:/home/app
    env_file:
      - ./../.env
